version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password1
      MYSQL_DATABASE: calendar_events_db
      MYSQL_PORT: 3306
    depends_on:
      - db
