version: "3.9"

services:
  lyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=calendar_events_db -user=root -password=password1 -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: calendar_events_db

    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=Etc/UTC' ]
    ports:
      - "3306:3306"
