CREATE TABLE conference_rooms (
  id BINARY(16) NOT NULL PRIMARY KEY,
  manager_id BINARY(16) NOT NULL,
  name VARCHAR(100) NOT NULL,
  address VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (manager_id) REFERENCES users(id)
) ENGINE=InnoDb;
